### ISSUE TITLE
开始更新所有群数据报错

### ISSUE THREAD

**Issue by JiangZongshi** [yuban10703/OPQ-SetuBot#23]
`2021-01-15 12:12:13 ERROR	出现错误 => Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10f6c52b0>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8888): Max retries exceeded with url: /v1/LuaApiCaller?funcname=GetGroupList&qq=3250718948 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f6c52b0>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/iotbot/action.py", line 748, in _baseSender
    rep = self.s.request(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8888): Max retries exceeded with url: /v1/LuaApiCaller?funcname=GetGroupList&qq=3250718948 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f6c52b0>: Failed to establish a new connection: [Errno 61] Connection refused'))

Traceback (most recent call last):
  File "/Users/apple/mySpace/OPQ-SetuBot/bot_setu_v3.py", line 1161, in <module>
    botdata.updateAllGroupData()
  File "/usr/local/lib/python3.9/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python3.9/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python3.9/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python3.9/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/Users/apple/mySpace/OPQ-SetuBot/bot_setu_v3.py", line 778, in updateAllGroupData
    data = action.get_group_list()['TroopList']
KeyError: 'TroopList'
`

**Comment by JiangZongshi** [comment]
是部署在mac上   防火墙已经关闭

**Comment by yuban10703** [comment]
端口正确么

**Comment by JiangZongshi** [comment]
> 端口正确么

  1 {
  2   "host": "127.0.0.1",
  3   "port": 8888,
  4   "webhook": false,
  5   "webhook_post_url": "http://localhost:5000",
  6   "webhook_timeout": 10
  7 }
这个没改

**Comment by yuban10703** [comment]
在获取群数据的时候，看看OPQ的日志有没有信息 截个图kk

**Comment by JiangZongshi** [comment]
> 在获取群数据的时候，看看OPQ的日志有没有信息 截个图kk

抱歉我不是python开发  所以思路未必正确。    我上面发出来的就是OPQ在启动时控制台打印出来的信息。 你说的日志信息应该就是这个吧？

**Comment by JiangZongshi** [comment]
![image](https://user-images.githubusercontent.com/11846840/104682242-31789e80-572f-11eb-92c4-93999c708b31.png)

**Comment by yuban10703** [comment]
就是OPQ的日志 不是Python的日志

**Comment by JiangZongshi** [comment]
![image](https://user-images.githubusercontent.com/11846840/104682296-4c4b1300-572f-11eb-90f5-d0642f8dd295.png)

**Comment by JiangZongshi** [comment]
> 就是OPQ的日志 不是Python的日志

OPQ的日志存放位置在哪里？文件目录里没有找到

**Comment by JiangZongshi** [comment]
![image](https://user-images.githubusercontent.com/11846840/104682426-9c29da00-572f-11eb-8d93-ce38125217c2.png)

**Comment by yuban10703** [comment]
emmm，你不会没打开OPQ吧。。。

**Comment by JiangZongshi** [comment]
> emmm，你不会没打开OPQ吧。。。

啊。。。OPQ指的不是这个脚本工程吗

**Comment by JiangZongshi** [comment]
直接在github看到的这个工程  第一次搭这个搭着玩的。。。还要装OPQ软件是吧。。。

**Comment by yuban10703** [comment]
阿哲。。点项目名称里的OPQ，去把那个项目部署了。。。

**Comment by JiangZongshi** [comment]
> 阿哲。。点项目名称里的OPQ，去把那个项目部署了。。。

![image](https://user-images.githubusercontent.com/11846840/104691111-9a1c4700-5740-11eb-8e26-30b9b5caa073.png)

**Comment by JiangZongshi** [comment]
![image](https://user-images.githubusercontent.com/11846840/104691151-a99b9000-5740-11eb-954f-d59a6dba1f16.png)

**Comment by JiangZongshi** [comment]
端口应该没错吧？

**Comment by JiangZongshi** [comment]
![Uploading image.png…]()

**Comment by JiangZongshi** [comment]
![image](https://user-images.githubusercontent.com/11846840/104692494-0ef08080-5743-11eb-99f5-546870b83bb9.png)

**Comment by yuban10703** [comment]
你OPQ还没登录QQ账号吧

**Comment by JiangZongshi** [comment]
> 你OPQ还没登录QQ账号吧

wiki漏看了两行  抱歉抱歉

**Comment by JiangZongshi** [comment]
![image](https://user-images.githubusercontent.com/11846840/104694376-0fd6e180-5746-11eb-940e-53d93d7243b6.png)

**Comment by yuban10703** [comment]
阿哲

**Comment by JiangZongshi** [comment]
> 阿哲

我把db目录删掉 就可以了。  虽然发出来的图是裂的。。。

**Comment by yuban10703** [comment]
图裂的可能是因为新号，挂久点就好了

**Comment by JiangZongshi** [comment]
![image](https://user-images.githubusercontent.com/11846840/104694992-fc784600-5746-11eb-909e-bfec2f4725f8.png)
socket 断开连接两次后就shutdown了

**Comment by yuban10703** [comment]
这是py框架有问题。。。
pip install python-socketio==4.6.0
试试

**Comment by JiangZongshi** [comment]
> 这是py框架有问题。。。
> pip install python-socketio==4.6.0
> 试试

![image](https://user-images.githubusercontent.com/11846840/104695684-18301c00-5748-11eb-9a84-8fb62bc1ebd9.png)
还不如刚才了，现在一会儿直接假死。   怎么恢复？

**Comment by yuban10703** [comment]
好家伙，我也不清楚，等我放假kk

**Comment by JiangZongshi** [comment]
> 好家伙，我也不清楚，等我放假kk

辛苦了~

**Comment by yuban10703** [comment]
试试 pip install python-engineio==3.14.2

**Comment by JiangZongshi** [comment]
> 试试 pip install python-engineio==3.14.2

可以了~就是全是裂图
