### ISSUE TITLE
使用pixiv接口会出现以下的报错，其他的正常。装了privoxy代理，国内服务器。

### ISSUE THREAD

**Issue by HeiLAAS** [yuban10703/OPQ-SetuBot#24]
`❌ 2021-01-19 01:41:32 ERROR	An error has been caught in function '_invoke_callbacks', process 'MainProcess' (30866), thread 'ThreadPoolExecutor-0_1' (140408688457472):
1|bot_setu_v3  | Traceback (most recent call last):
1|bot_setu_v3  |   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 662, in urlopen
1|bot_setu_v3  |     self._prepare_proxy(conn)
1|bot_setu_v3  |     │    │              └ None
1|bot_setu_v3  |     │    └ <function HTTPSConnectionPool._prepare_proxy at 0x7fb37b7539d0>
1|bot_setu_v3  |     └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fb378307340>
1|bot_setu_v3  |   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 950, in _prepare_proxy
1|bot_setu_v3  |     conn.connect()
1|bot_setu_v3  |     │    └ <function VerifiedHTTPSConnection.connect at 0x7fb37b1dd4c0>
1|bot_setu_v3  |     └ <urllib3.connection.VerifiedHTTPSConnection object at 0x7fb378250310>
1|bot_setu_v3  |   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 322, in connect
1|bot_setu_v3  |     self._tunnel()
1|bot_setu_v3  |     │    └ <function HTTPConnection._tunnel at 0x7fb37b5cc4c0>
1|bot_setu_v3  |     └ <urllib3.connection.VerifiedHTTPSConnection object at 0x7fb378250310>
1|bot_setu_v3  |   File "/usr/lib/python3.8/http/client.py", line 904, in _tunnel
1|bot_setu_v3  |     raise OSError("Tunnel connection failed: %d %s" % (code,
1|bot_setu_v3  |                                                        └ 503
1|bot_setu_v3  | OSError: Tunnel connection failed: 503 Connect failed
1|bot_setu_v3  | During handling of the above exception, another exception occurred:
1|bot_setu_v3  | Traceback (most recent call last):
1|bot_setu_v3  |   File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 439, in send
1|bot_setu_v3  |     resp = conn.urlopen(
1|bot_setu_v3  |            │    └ <function HTTPConnectionPool.urlopen at 0x7fb37b753820>
1|bot_setu_v3  |            └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fb378307340>
1|bot_setu_v3  |   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
1|bot_setu_v3  |     retries = retries.increment(
1|bot_setu_v3  |               │       └ <function Retry.increment at 0x7fb37b1d2e50>
1|bot_setu_v3  |               └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
1|bot_setu_v3  |   File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
1|bot_setu_v3  |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
1|bot_setu_v3  |           │             │      │    │        │             └ 'too many error responses'
1|bot_setu_v3  |           │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
1|bot_setu_v3  |           │             │      │    └ ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Connect failed'))
1|bot_setu_v3  |           │             │      └ '/c/600x1200_90_webp/img-master/img/2013/10/14/23/40/52/39125777_p0_master1200.jpg'
1|bot_setu_v3  |           │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fb378307340>
1|bot_setu_v3  |           └ <class 'urllib3.exceptions.MaxRetryError'>
1|bot_setu_v3  | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='i.pximg.net', port=443): Max retries exceeded with url: /c/600x1200_90_webp/img-master/img/2013/10/14/23/40/52/39125777_p0_master1200.jpg (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Connect failed')))
1|bot_setu_v3  | During handling of the above exception, another exception occurred:
1|bot_setu_v3  | Traceback (most recent call last):
1|bot_setu_v3  |   File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
1|bot_setu_v3  |     self._bootstrap_inner()
1|bot_setu_v3  |     │    └ <function Thread._bootstrap_inner at 0x7fb37b87aca0>
1|bot_setu_v3  |     └ <Thread(ThreadPoolExecutor-0_1, started daemon 140408688457472)>
1|bot_setu_v3  |   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
1|bot_setu_v3  |     self.run()
1|bot_setu_v3  |     │    └ <function Thread.run at 0x7fb37b87a9d0>
1|bot_setu_v3  |     └ <Thread(ThreadPoolExecutor-0_1, started daemon 140408688457472)>
1|bot_setu_v3  |   File "/usr/lib/python3.8/threading.py", line 870, in run
1|bot_setu_v3  |     self._target(*self._args, **self._kwargs)
1|bot_setu_v3  |     │    │        │    │        │    └ {}
1|bot_setu_v3  |     │    │        │    │        └ <Thread(ThreadPoolExecutor-0_1, started daemon 140408688457472)>
1|bot_setu_v3  |     │    │        │    └ (<weakref at 0x7fb378492040; to 'ThreadPoolExecutor' at 0x7fb378d4ba90>, <_queue.SimpleQueue object at 0x7fb378d4a9a0>, None,...
1|bot_setu_v3  |     │    │        └ <Thread(ThreadPoolExecutor-0_1, started daemon 140408688457472)>
1|bot_setu_v3  |     │    └ <function _worker at 0x7fb37af1e670>
1|bot_setu_v3  |     └ <Thread(ThreadPoolExecutor-0_1, started daemon 140408688457472)>
1|bot_setu_v3  |   File "/usr/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
1|bot_setu_v3  |     work_item.run()
1|bot_setu_v3  |     │         └ <function _WorkItem.run at 0x7fb37af1e790>
1|bot_setu_v3  |     └ <concurrent.futures.thread._WorkItem object at 0x7fb3783467f0>
1|bot_setu_v3  |   File "/usr/lib/python3.8/concurrent/futures/thread.py", line 59, in run
1|bot_setu_v3  |     self.future.set_exception(exc)
1|bot_setu_v3  |     │    │      │             └ ProxyError(MaxRetryError("HTTPSConnectionPool(host='i.pximg.net', port=443): Max retries exceeded with url: /c/600x1200_90_we...
1|bot_setu_v3  |     │    │      └ <function Future.set_exception at 0x7fb37af1e040>
1|bot_setu_v3  |     │    └ <Future at 0x7fb37838f3a0 state=finished raised ProxyError>
1|bot_setu_v3  |     └ <concurrent.futures.thread._WorkItem object at 0x7fb3783467f0>
1|bot_setu_v3  |   File "/usr/lib/python3.8/concurrent/futures/_base.py", line 545, in set_exception
1|bot_setu_v3  |     self._invoke_callbacks()
1|bot_setu_v3  |     │    └ <function Future._invoke_callbacks at 0x7fb37af1c940>
1|bot_setu_v3  |     └ <Future at 0x7fb37838f3a0 state=finished raised ProxyError>
1|bot_setu_v3  | > File "/usr/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
1|bot_setu_v3  |     callback(self)
1|bot_setu_v3  |     │        └ <Future at 0x7fb37838f3a0 state=finished raised ProxyError>
1|bot_setu_v3  |     └ <bound method IOTBOT.__thread_pool_callback of IOTBOT <2026328797> <host-http://127.0.0.1> <port-8888>>
1|bot_setu_v3  |   File "/usr/local/lib/python3.8/dist-packages/iotbot/client.py", line 400, in __thread_pool_callback
1|bot_setu_v3  |     raise worker_exception
1|bot_setu_v3  |           └ ProxyError(MaxRetryError("HTTPSConnectionPool(host='i.pximg.net', port=443): Max retries exceeded with url: /c/600x1200_90_we...
1|bot_setu_v3  |   File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
1|bot_setu_v3  |     result = self.fn(*self.args, **self.kwargs)
1|bot_setu_v3  |              │    │   │    │       │    └ {}
1|bot_setu_v3  |              │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fb3783467f0>
1|bot_setu_v3  |              │    │   │    └ [<iotbot.model.GroupMsg object at 0x7fb378346cd0>]
1|bot_setu_v3  |              │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fb3783467f0>
1|bot_setu_v3  |              │    └ <function in_content.<locals>.deco.<locals>.inner at 0x7fb378d64700>
1|bot_setu_v3  |              └ <concurrent.futures.thread._WorkItem object at 0x7fb3783467f0>
1|bot_setu_v3  |   File "/usr/local/lib/python3.8/dist-packages/iotbot/decorators.py", line 17, in inner
1|bot_setu_v3  |     return func(ctx)
1|bot_setu_v3  |            │    └ <iotbot.model.GroupMsg object at 0x7fb378346cd0>
1|bot_setu_v3  |            └ <function group_setu at 0x7fb378d64670>
1|bot_setu_v3  |   File "/root/OPQ-SetuBot/bot_setu_v3.py", line 1012, in group_setu
1|bot_setu_v3  |     Setu(ctx, info[2], info[1], info[3]).main()
1|bot_setu_v3  |     │    │    │        │        └ <re.Match object; span=(0, 7), match='来点KLK色图'>
1|bot_setu_v3  |     │    │    │        └ <re.Match object; span=(0, 7), match='来点KLK色图'>
1|bot_setu_v3  |     │    │    └ <re.Match object; span=(0, 7), match='来点KLK色图'>
1|bot_setu_v3  |     │    └ <iotbot.model.GroupMsg object at 0x7fb378346cd0>
1|bot_setu_v3  |     └ <class '__main__.Setu'>
1|bot_setu_v3  |   File "/root/OPQ-SetuBot/bot_setu_v3.py", line 499, in main
1|bot_setu_v3  |     self.group_or_temp()
1|bot_setu_v3  |     │    └ <function Setu.group_or_temp at 0x7fb378d625e0>
1|bot_setu_v3  |     └ <__main__.Setu object at 0x7fb3783467c0>
1|bot_setu_v3  |   File "/root/OPQ-SetuBot/bot_setu_v3.py", line 464, in group_or_temp
1|bot_setu_v3  |     self.processing_and_inspect()
1|bot_setu_v3  |     │    └ <function Setu.processing_and_inspect at 0x7fb378d62550>
1|bot_setu_v3  |     └ <__main__.Setu object at 0x7fb3783467c0>
1|bot_setu_v3  |   File "/root/OPQ-SetuBot/bot_setu_v3.py", line 444, in processing_and_inspect
1|bot_setu_v3  |     self.send()
1|bot_setu_v3  |     │    └ <function Setu._freq.<locals>.wrapper at 0x7fb378d62820>
1|bot_setu_v3  |     └ <__main__.Setu object at 0x7fb3783467c0>
1|bot_setu_v3  |   File "/root/OPQ-SetuBot/bot_setu_v3.py", line 408, in wrapper
1|bot_setu_v3  |     func(self, *args, **kwargs)
1|bot_setu_v3  |     │    │      │       └ {}
1|bot_setu_v3  |     │    │      └ ()
1|bot_setu_v3  |     │    └ <__main__.Setu object at 0x7fb3783467c0>
1|bot_setu_v3  |     └ <function Setu.send at 0x7fb378d62790>
1|bot_setu_v3  |   File "/root/OPQ-SetuBot/bot_setu_v3.py", line 509, in send
1|bot_setu_v3  |     self.api_pixiv()
1|bot_setu_v3  |     │    └ <function Setu.api_pixiv at 0x7fb378d62430>
1|bot_setu_v3  |     └ <__main__.Setu object at 0x7fb3783467c0>
1|bot_setu_v3  |   File "/root/OPQ-SetuBot/bot_setu_v3.py", line 370, in api_pixiv
1|bot_setu_v3  |     img_webp = requests.get(setu['image_urls']['large'],
1|bot_setu_v3  |                │        │   └ {'id': 39125777, 'title': 'HENTAI', 'type': 'illust', 'image_urls': {'square_medium': 'https://i.pximg.net/c/540x540_10_webp/...
1|bot_setu_v3  |                │        └ <function get at 0x7fb37af059d0>
1|bot_setu_v3  |                └ <module 'requests' from '/usr/local/lib/python3.8/dist-packages/requests/__init__.py'>
1|bot_setu_v3  |   File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 76, in get
1|bot_setu_v3  |     return request('get', url, params=params, **kwargs)
1|bot_setu_v3  |            │              │           │         └ {'headers': {'Referer': 'https://www.pixiv.net'}, 'allow_redirects': True}
1|bot_setu_v3  |            │              │           └ None
1|bot_setu_v3  |            │              └ 'https://i.pximg.net/c/600x1200_90_webp/img-master/img/2013/10/14/23/40/52/39125777_p0_master1200.jpg'
1|bot_setu_v3  |            └ <function request at 0x7fb37af2bca0>
1|bot_setu_v3  |   File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 61, in request
1|bot_setu_v3  |     return session.request(method=method, url=url, **kwargs)
1|bot_setu_v3  |            │       │              │           │      └ {'params': None, 'headers': {'Referer': 'https://www.pixiv.net'}, 'allow_redirects': True}
1|bot_setu_v3  |            │       │              │           └ 'https://i.pximg.net/c/600x1200_90_webp/img-master/img/2013/10/14/23/40/52/39125777_p0_master1200.jpg'
1|bot_setu_v3  |            │       │              └ 'get'
1|bot_setu_v3  |            │       └ <function Session.request at 0x7fb37af05160>
1|bot_setu_v3  |            └ <requests.sessions.Session object at 0x7fb378307df0>
1|bot_setu_v3  |   File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 542, in request
1|bot_setu_v3  |     resp = self.send(prep, **send_kwargs)
1|bot_setu_v3  |            │    │    │       └ {'timeout': None, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict([('http', 'http://127.0.0.1:8118'), ('https...
1|bot_setu_v3  |            │    │    └ <PreparedRequest [GET]>
1|bot_setu_v3  |            │    └ <function Session.send at 0x7fb37af055e0>
1|bot_setu_v3  |            └ <requests.sessions.Session object at 0x7fb378307df0>
1|bot_setu_v3  |   File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 655, in send
1|bot_setu_v3  |     r = adapter.send(request, **kwargs)
1|bot_setu_v3  |         │       │    │          └ {'timeout': None, 'verify': True, 'proxies': OrderedDict([('http', 'http://127.0.0.1:8118'), ('https', 'http://127.0.0.1:8118...
1|bot_setu_v3  |         │       │    └ <PreparedRequest [GET]>
1|bot_setu_v3  |         │       └ <function HTTPAdapter.send at 0x7fb37af03a60>
1|bot_setu_v3  |         └ <requests.adapters.HTTPAdapter object at 0x7fb378307be0>
1|bot_setu_v3  |   File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 510, in send
1|bot_setu_v3  |     raise ProxyError(e, request=request)
1|bot_setu_v3  |           │                     └ <PreparedRequest [GET]>
1|bot_setu_v3  |           └ <class 'requests.exceptions.ProxyError'>
1|bot_setu_v3  | requests.exceptions.ProxyError: HTTPSConnectionPool(host='i.pximg.net', port=443): Max retries exceeded with url: /c/600x1200_90_webp/img-master/img/2013/10/14/23/40/52/39125777_p0_master1200.jpg (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Connect failed')))
`

**Comment by HeiLAAS** [comment]
好了··重装了下python
