### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by sayri23** [yuban10703/OPQ-SetuBot#30]
![TD@%JMHZHB@%{EC7RB`O4CH](https://user-images.githubusercontent.com/62638560/108622427-bc0d9580-7473-11eb-8495-e1d464d77b1e.png)

**Comment by yuban10703** [comment]
换python3.8+版本
这个是3.6吧.......

**Comment by sayri23** [comment]
版本问题吗？

**Comment by yuban10703** [comment]
python版本问题...
你这Ubuntu有点旧啊...

**Comment by sayri23** [comment]
腾讯云，新用户的试用，只有18.04.01 LTS

**Comment by yuban10703** [comment]
那就自己装python3.8+吧....

**Comment by sayri23** [comment]
> 那就自己装python3.8+吧....

3.8安装完后模块也要重新安装吗？

**Comment by yuban10703** [comment]
嗯,切到3.8的pip装模块

**Comment by sayri23** [comment]
> 嗯,切到3.8的pip装模块

  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip._internal'

**Comment by yuban10703** [comment]
蛤?...

**Comment by sayri23** [comment]
> > 嗯,切到3.8的pip装模块
> 
> File "/usr/local/bin/pip", line 7, in
> from pip._internal.cli.main import main
> ModuleNotFoundError: No module named 'pip._internal'

是与旧版冲突了？

**Comment by yuban10703** [comment]
看看  pip3 -V

**Comment by sayri23** [comment]
root@VM-4-9-ubuntu:/home/lighthouse/OPQ-SetuBot# pip3 -V
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 7, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip._internal'

**Comment by yuban10703** [comment]
阿哲

**Comment by yuban10703** [comment]
which pip3

**Comment by yuban10703** [comment]
cat /usr/local/bin/pip3
看看

**Comment by sayri23** [comment]
root@VM-4-9-ubuntu:/home/lighthouse/OPQ-SetuBot# which pip3
/usr/local/bin/pip3

**Comment by sayri23** [comment]
> cat /usr/local/bin/pip3
> 看看

root@VM-4-9-ubuntu:/home/lighthouse/OPQ-SetuBot# cat /usr/local/bin/pip3
#!/usr/bin/python3

# -*- coding: utf-8 -*-
import re
import sys

from pip._internal.cli.main import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

**Comment by yuban10703** [comment]
python3 -V 看看

**Comment by sayri23** [comment]
root@VM-4-9-ubuntu:/home/lighthouse/OPQ-SetuBot# python3 -V 
Python 3.8.8

**Comment by yuban10703** [comment]
好家伙

**Comment by sayri23** [comment]
问题出在哪了？

**Comment by yuban10703** [comment]
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py --force-reinstall

刚刚百度找的,你试试?.....

**Comment by yuban10703** [comment]
> 问题出在哪了？

没遇到过...

**Comment by sayri23** [comment]
> curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
> python3 get-pip.py --force-reinstall
> 
> 刚刚百度找的,你试试?.....

root@VM-4-9-ubuntu:/home/lighthouse/OPQ-SetuBot# curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1882k  100 1882k    0     0   158k      0  0:00:11  0:00:11 --:--:--  224k
root@VM-4-9-ubuntu:/home/lighthouse/OPQ-SetuBot# python3 get-pip.py --force-reinstall
Looking in indexes: http://mirrors.tencentyun.com/pypi/simple
Collecting pip
  Downloading http://mirrors.tencentyun.com/pypi/packages/fe/ef/60d7ba03b5c442309ef42e7d69959f73aacccd0d86008362a681c4698e83/pip-21.0.1-py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 809 kB/s 
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-21.0.1

**Comment by sayri23** [comment]
模块安装成功辽！

**Comment by yuban10703** [comment]
那就好..

**Comment by sayri23** [comment]
> 那就好..

root@VM-4-9-ubuntu:/home/lighthouse/OPQ-SetuBot# python3 bot.py
Traceback (most recent call last):
  File "bot.py", line 6, in <module>
    bot = Botoy(qq=config.botqq,
  File "/usr/local/lib/python3.8/dist-packages/botoy/client.py", line 102, in __init__
    self.plugMgr.load_plugins()
  File "/usr/local/lib/python3.8/dist-packages/botoy/plugin.py", line 76, in load_plugins
    module = importlib.import_module(
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lighthouse/OPQ-SetuBot/plugins/bot_sysinfo.py", line 4, in <module>
    import psutil
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 100, in <module>
    from . import _pslinux as _psplatform
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 26, in <module>
    from . import _psutil_linux as cext
ImportError: cannot import name '_psutil_linux' from partially initialized module 'psutil' (most likely due to a circular import) (/usr/lib/python3/dist-packages/psutil/__init__.py)

**Comment by sayri23** [comment]
啊这

**Comment by yuban10703** [comment]
阿哲

**Comment by sayri23** [comment]
头大

**Comment by yuban10703** [comment]
python3

import psutil
试试


用ctrl + z可以退出

**Comment by sayri23** [comment]
> python3
> 
> import psutil
> 试试
> 
> 用ctrl + z可以退出

root@VM-4-9-ubuntu:/home/lighthouse# python3
Python 3.8.8 (default, Feb 20 2021, 21:09:14) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import psutil
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 100, in <module>
    from . import _pslinux as _psplatform
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 26, in <module>
    from . import _psutil_linux as cext
ImportError: cannot import name '_psutil_linux' from partially initialized module 'psutil' (most likely due to a circular import) (/usr/lib/python3/dist-packages/psutil/__init__.py)
>>>

**Comment by yuban10703** [comment]
好像是这个模块出问题了
pip3 uninstall psutil
pip3 install psutil

**Comment by sayri23** [comment]
> 好像是这个模块出问题了
> pip3 uninstall psutil
> pip3 install psutil

lighthouse@VM-4-9-ubuntu:~$ pip3 uninstall psutil
Found existing installation: psutil 5.4.2
ERROR: Cannot uninstall 'psutil'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by sayri23** [comment]
> 好像是这个模块出问题了
> pip3 uninstall psutil
> pip3 install psutil

lighthouse@VM-4-9-ubuntu:~$ pip3 install psutil
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psutil in /usr/lib/python3/dist-packages (5.4.2)

**Comment by yuban10703** [comment]
阿哲

**Comment by sayri23** [comment]
> 阿哲

进入root账户后

**Comment by sayri23** [comment]
root@VM-4-9-ubuntu:/home/lighthouse/OPQ-SetuBot# pip3 uninstall psutil
Found existing installation: psutil 5.4.2
ERROR: Cannot uninstall 'psutil'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
root@VM-4-9-ubuntu:/home/lighthouse/OPQ-SetuBot# pip3 install psutil
Looking in indexes: http://mirrors.tencentyun.com/pypi/simple
Requirement already satisfied: psutil in /usr/lib/python3/dist-packages (5.4.2)

**Comment by yuban10703** [comment]
pip3 show psutil

**Comment by sayri23** [comment]
> pip3 show psutil

root@VM-4-9-ubuntu:/home/lighthouse/OPQ-SetuBot# pip3 show psutil
Name: psutil
Version: 5.4.2
Summary: Cross-platform lib for process and system monitoring in Python.
Home-page: https://github.com/giampaolo/psutil
Author: Giampaolo Rodola
Author-email: g.rodola@gmail.com
License: BSD
Location: /usr/lib/python3/dist-packages
Requires: 
Required-by:

**Comment by yuban10703** [comment]
rm -rf /usr/lib/python3/dist-packages/psutil*

**Comment by yuban10703** [comment]
pip3 install psutil

**Comment by sayri23** [comment]
root@VM-4-9-ubuntu:/home/lighthouse/OPQ-SetuBot# rm -rf /usr/lib/python3/dist-packages/psutil*
root@VM-4-9-ubuntu:/home/lighthouse/OPQ-SetuBot# pip3 install psutil
Looking in indexes: http://mirrors.tencentyun.com/pypi/simple
Collecting psutil
  Downloading http://mirrors.tencentyun.com/pypi/packages/3b/c2/78109a12da9febb2f965abf29da6f81b0a3f2b89a7b59d88b759e68dc6db/psutil-5.8.0-cp38-cp38-manylinux2010_x86_64.whl (296 kB)
     |████████████████████████████████| 296 kB 1.6 MB/s 
Installing collected packages: psutil
Successfully installed psutil-5.8.0

**Comment by yuban10703** [comment]
试试,能不能运行bot了

**Comment by sayri23** [comment]
> 试试,能不能运行bot了

好像还少模块
Traceback (most recent call last):
  File "/usr/lib/command-not-found", line 28, in <module>
    from CommandNotFound import CommandNotFound
  File "/usr/lib/python3/dist-packages/CommandNotFound/CommandNotFound.py", line 19, in <module>
    from CommandNotFound.db.db import SqliteDatabase
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/db.py", line 5, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

**Comment by sayri23** [comment]
root@VM-4-9-ubuntu:/home/lighthouse/OPQ-SetuBot# python3 bot.py
Traceback (most recent call last):
  File "bot.py", line 6, in <module>
    bot = Botoy(qq=config.botqq,
  File "/usr/local/lib/python3.8/dist-packages/botoy/client.py", line 102, in __init__
    self.plugMgr.load_plugins()
  File "/usr/local/lib/python3.8/dist-packages/botoy/plugin.py", line 76, in load_plugins
    module = importlib.import_module(
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lighthouse/OPQ-SetuBot/plugins/bot_yuanShen.py", line 4, in <module>
    from PIL import Image
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 60, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)

**Comment by yuban10703** [comment]
........

rm -rf /usr/local/lib/python3.8/dist-packages/*

**Comment by yuban10703** [comment]
pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by yuban10703** [comment]
rm -rf /usr/lib/python3/dist-packages/*

**Comment by yuban10703** [comment]
pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by sayri23** [comment]
> pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

root@VM-4-9-ubuntu:/home/lighthouse/OPQ-SetuBot# rm -rf /usr/lib/python3/dist-packages/*
root@VM-4-9-ubuntu:/home/lighthouse/OPQ-SetuBot# pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'

**Comment by yuban10703** [comment]
艹,我把pip也删了..
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py --force-reinstall

**Comment by sayri23** [comment]
> 艹,我把pip也删了..
> curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
> python3 get-pip.py --force-reinstall

阿哲

**Comment by sayri23** [comment]
root@VM-4-9-ubuntu:/home/lighthouse/OPQ-SetuBot# curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1882k  100 1882k    0     0  22111      0  0:01:27  0:01:27 --:--:-- 34936
root@VM-4-9-ubuntu:/home/lighthouse/OPQ-SetuBot# python3 get-pip.py --force-reinstall
ERROR: Exception:
Traceback (most recent call last):
  File "/tmp/tmprujumqtw/pip.zip/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/tmp/tmprujumqtw/pip.zip/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/tmp/tmprujumqtw/pip.zip/pip/_internal/commands/install.py", line 267, in run
    session = self.get_default_session(options)
  File "/tmp/tmprujumqtw/pip.zip/pip/_internal/cli/req_command.py", line 76, in get_default_session
    self._session = self.enter_context(self._build_session(options))
  File "/tmp/tmprujumqtw/pip.zip/pip/_internal/cli/req_command.py", line 86, in _build_session
    session = PipSession(
  File "/tmp/tmprujumqtw/pip.zip/pip/_internal/network/session.py", line 245, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/tmp/tmprujumqtw/pip.zip/pip/_internal/network/session.py", line 132, in user_agent
    zip(["name", "version", "id"], distro.linux_distribution()),
  File "/tmp/tmprujumqtw/pip.zip/pip/_vendor/distro.py", line 125, in linux_distribution
    return _distro.linux_distribution(full_distribution_name)
  File "/tmp/tmprujumqtw/pip.zip/pip/_vendor/distro.py", line 681, in linux_distribution
    self.version(),
  File "/tmp/tmprujumqtw/pip.zip/pip/_vendor/distro.py", line 741, in version
    self.lsb_release_attr('release'),
  File "/tmp/tmprujumqtw/pip.zip/pip/_vendor/distro.py", line 903, in lsb_release_attr
    return self._lsb_release_info.get(attribute, '')
  File "/tmp/tmprujumqtw/pip.zip/pip/_vendor/distro.py", line 556, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/tmp/tmprujumqtw/pip.zip/pip/_vendor/distro.py", line 1014, in _lsb_release_info
    stdout = subprocess.check_output(cmd, stderr=devnull)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1.
Traceback (most recent call last):
  File "get-pip.py", line 24184, in <module>
    main()
  File "get-pip.py", line 139, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 121, in bootstrap
    sys.exit(pip_entry_point(args))
  File "/tmp/tmprujumqtw/pip.zip/pip/_internal/cli/main.py", line 73, in main
  File "/tmp/tmprujumqtw/pip.zip/pip/_internal/cli/base_command.py", line 111, in main
  File "/tmp/tmprujumqtw/pip.zip/pip/_internal/cli/base_command.py", line 226, in _main
  File "/tmp/tmprujumqtw/pip.zip/pip/_internal/cli/req_command.py", line 145, in handle_pip_version_check
  File "/tmp/tmprujumqtw/pip.zip/pip/_internal/cli/req_command.py", line 86, in _build_session
  File "/tmp/tmprujumqtw/pip.zip/pip/_internal/network/session.py", line 245, in __init__
  File "/tmp/tmprujumqtw/pip.zip/pip/_internal/network/session.py", line 132, in user_agent
  File "/tmp/tmprujumqtw/pip.zip/pip/_vendor/distro.py", line 125, in linux_distribution
  File "/tmp/tmprujumqtw/pip.zip/pip/_vendor/distro.py", line 681, in linux_distribution
  File "/tmp/tmprujumqtw/pip.zip/pip/_vendor/distro.py", line 741, in version
  File "/tmp/tmprujumqtw/pip.zip/pip/_vendor/distro.py", line 903, in lsb_release_attr
  File "/tmp/tmprujumqtw/pip.zip/pip/_vendor/distro.py", line 556, in __get__
  File "/tmp/tmprujumqtw/pip.zip/pip/_vendor/distro.py", line 1014, in _lsb_release_info
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1.

**Comment by yuban10703** [comment]
...可能没救了
python3 get-pip.py
试试....

**Comment by sayri23** [comment]
root@VM-4-9-ubuntu:/home/lighthouse/OPQ-SetuBot# python3 get-pip.py
ERROR: Exception:
Traceback (most recent call last):
  File "/tmp/tmpokw93k0v/pip.zip/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/tmp/tmpokw93k0v/pip.zip/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/tmp/tmpokw93k0v/pip.zip/pip/_internal/commands/install.py", line 267, in run
    session = self.get_default_session(options)
  File "/tmp/tmpokw93k0v/pip.zip/pip/_internal/cli/req_command.py", line 76, in get_default_session
    self._session = self.enter_context(self._build_session(options))
  File "/tmp/tmpokw93k0v/pip.zip/pip/_internal/cli/req_command.py", line 86, in _build_session
    session = PipSession(
  File "/tmp/tmpokw93k0v/pip.zip/pip/_internal/network/session.py", line 245, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/tmp/tmpokw93k0v/pip.zip/pip/_internal/network/session.py", line 132, in user_agent
    zip(["name", "version", "id"], distro.linux_distribution()),
  File "/tmp/tmpokw93k0v/pip.zip/pip/_vendor/distro.py", line 125, in linux_distribution
    return _distro.linux_distribution(full_distribution_name)
  File "/tmp/tmpokw93k0v/pip.zip/pip/_vendor/distro.py", line 681, in linux_distribution
    self.version(),
  File "/tmp/tmpokw93k0v/pip.zip/pip/_vendor/distro.py", line 741, in version
    self.lsb_release_attr('release'),
  File "/tmp/tmpokw93k0v/pip.zip/pip/_vendor/distro.py", line 903, in lsb_release_attr
    return self._lsb_release_info.get(attribute, '')
  File "/tmp/tmpokw93k0v/pip.zip/pip/_vendor/distro.py", line 556, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/tmp/tmpokw93k0v/pip.zip/pip/_vendor/distro.py", line 1014, in _lsb_release_info
    stdout = subprocess.check_output(cmd, stderr=devnull)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1.
Traceback (most recent call last):
  File "get-pip.py", line 24184, in <module>
    main()
  File "get-pip.py", line 139, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 121, in bootstrap
    sys.exit(pip_entry_point(args))
  File "/tmp/tmpokw93k0v/pip.zip/pip/_internal/cli/main.py", line 73, in main
  File "/tmp/tmpokw93k0v/pip.zip/pip/_internal/cli/base_command.py", line 111, in main
  File "/tmp/tmpokw93k0v/pip.zip/pip/_internal/cli/base_command.py", line 226, in _main
  File "/tmp/tmpokw93k0v/pip.zip/pip/_internal/cli/req_command.py", line 145, in handle_pip_version_check
  File "/tmp/tmpokw93k0v/pip.zip/pip/_internal/cli/req_command.py", line 86, in _build_session
  File "/tmp/tmpokw93k0v/pip.zip/pip/_internal/network/session.py", line 245, in __init__
  File "/tmp/tmpokw93k0v/pip.zip/pip/_internal/network/session.py", line 132, in user_agent
  File "/tmp/tmpokw93k0v/pip.zip/pip/_vendor/distro.py", line 125, in linux_distribution
  File "/tmp/tmpokw93k0v/pip.zip/pip/_vendor/distro.py", line 681, in linux_distribution
  File "/tmp/tmpokw93k0v/pip.zip/pip/_vendor/distro.py", line 741, in version
  File "/tmp/tmpokw93k0v/pip.zip/pip/_vendor/distro.py", line 903, in lsb_release_attr
  File "/tmp/tmpokw93k0v/pip.zip/pip/_vendor/distro.py", line 556, in __get__
  File "/tmp/tmpokw93k0v/pip.zip/pip/_vendor/distro.py", line 1014, in _lsb_release_info
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1.


啊这

**Comment by yuban10703** [comment]
find / -name lsb_release

**Comment by sayri23** [comment]
> find / -name lsb_release

root@VM-4-9-ubuntu:/home/lighthouse/OPQ-SetuBot# find / -name lsb_release
/usr/bin/lsb_release

**Comment by yuban10703** [comment]
mv /usr/bin/lsb_release /usr/bin/lsb_release1

**Comment by yuban10703** [comment]
python3 get-pip.py

**Comment by sayri23** [comment]
> python3 get-pip.py

pip安装成功

**Comment by yuban10703** [comment]
pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by sayri23** [comment]
> pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

好了

**Comment by yuban10703** [comment]
试试bot能不能启动..

**Comment by sayri23** [comment]
> 试试bot能不能启动..

oot@VM-4-9-ubuntu:/home/lighthouse/OPQ-SetuBot# python3 bot.py
ℹ️ 2021-02-21 20:28:04 INFO      无pixivToken文件,尝试获取~
ℹ️ 2021-02-21 20:28:04 INFO      获取Pixiv_token~
+---------------------+-------+------------------------------------------------------------+
|       Receiver      | Count |                            Info                            |
+---------------------+-------+------------------------------------------------------------+
| Friend Msg Receiver |   6   |      addsetu/sysinfo/searchPicture/setu/cmd/yuanShen       |
| Group  Msg Receiver |   7   | setuRevoke/addsetu/sysinfo/searchPicture/setu/cmd/yuanShen |
| Event      Receiver |   1   |                        eventMonitor                        |
+---------------------+-------+------------------------------------------------------------+
+-----------------+
| Removed Plugins |
+-----------------+
|                 |
+-----------------+
ℹ️ 2021-02-21 20:28:04 INFO      开始更新所有群数据~
❌ 2021-02-21 20:28:04 ERROR     请求出错: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/httpx/_exceptions.py", line 326, in map_exceptions
    yield
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 861, in _send_single_request
    (status_code, headers, stream, ext) = transport.request(
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_sync/connection_pool.py", line 218, in request
    response = connection.request(
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_sync/connection.py", line 93, in request
    self.socket = self._open_socket(timeout)
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_sync/connection.py", line 119, in _open_socket
    return self.backend.open_tcp_stream(
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_backends/sync.py", line 143, in open_tcp_stream
    return SyncSocketStream(sock=sock)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/botoy/action.py", line 603, in baseRequest
    resp = self.c.request(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 733, in request
    return self.send(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 767, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 805, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 837, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 861, in _send_single_request
    (status_code, headers, stream, ext) = transport.request(
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ConnectError: [Errno 111] Connection refused

✔️ 2021-02-21 20:28:04 SUCCESS   更新群信息成功~

**Comment by yuban10703** [comment]
你OPQBot运行了么....
还有pixiv现在博纳云,先关掉..

**Comment by sayri23** [comment]
OPQ运行了

**Comment by yuban10703** [comment]
你config.ini是什么样子

**Comment by sayri23** [comment]
> 你config.ini是什么样子

![Uploading }NFJ1ARP0_FDEWEDK][{~YS.png…]()

**Comment by sayri23** [comment]
> 你config.ini是什么样子

![}NFJ1ARP0_FDEWEDK {~YS](https://user-images.githubusercontent.com/62638560/108625166-48c04f80-7484-11eb-8149-0a21ea65bb7b.png)

**Comment by sayri23** [comment]
端口忘了改

**Comment by yuban10703** [comment]
....

**Comment by sayri23** [comment]
> ....

![06D3M(M7_}LD4)D5EKMW4KD](https://user-images.githubusercontent.com/62638560/108625212-a359ab80-7484-11eb-8334-4f046d00dbe5.png)

**Comment by yuban10703** [comment]
看起来是跑起来了

**Comment by sayri23** [comment]
然后呢

**Comment by yuban10703** [comment]
然后就没然后了啊.....
看wiki的指令去群里测试呀

**Comment by sayri23** [comment]
原神抽卡没问题
色图呢，打开api？

**Comment by yuban10703** [comment]
看看log

**Comment by sayri23** [comment]
> 看看log

哪里看？

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/108625483-27606300-7486-11eb-9c65-133a6c4900ef.png)
就这个

**Comment by sayri23** [comment]
![0_1ZB}WMF TD)L~GOMW2P$R](https://user-images.githubusercontent.com/62638560/108625511-45c65e80-7486-11eb-942b-37685d3776cf.png)
显示发送了，但并没有看到

**Comment by yuban10703** [comment]
那就是风控了,等几天就好了,还有pixivapi别开,那个还没修

**Comment by sayri23** [comment]
> 那就是风控了,等几天就好了,还有pixivapi别开,那个还没修

哪色图现在就是看不了吧

**Comment by yuban10703** [comment]
OPQ多挂几天,风控解了就能发了

**Comment by sayri23** [comment]
好的
